apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "svc.fullname" . }}
  labels:
    {{- include "svc.labels" . | nindent 4 }}
data:
  COGNITO_ISSUER: {{ .Values.cognito.issuer | quote }}
  COGNITO_CLIENT_ID: {{ .Values.cognito.clientId | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.corsAllowedOrigins | quote }}
